version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres
    restart: always
    env_file: .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    depends_on:
      - db
    env_file: .env.example
    volumes:
      - static:/static_backend
      - media:/app/media

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
