version: '3.3'

volumes:
  pg_data:
#   static:
#   media:

services:
  db:
    image: postgres
    restart: always
    env_file: .env.example
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ../backend/
    depends_on:
      - db
    env_file: .env.example
    # volumes:
    #   - static:/static_backend
    #   - media:/app/media

  nginx:
    build: ../nginx/
    ports:
      - "8080:80"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
    #   - ../frontend/build:/usr/share/nginx/html/
    #   - ../docs/:/usr/share/nginx/html/api/docs/
