"""
Модуль констант для проекта.
"""

"""
Константы для paginators.py
"""
PAGE_SIZE_PAGINATORS = 6

"""
Константы для моделей recipes
"""
# Ингредиенты
INGREGIENT_NAME_MAX_LENGTH = 200
INGREGIENT_MEASUREMENT_UNIT_NAME_MAX_LENGTH = 200

# Теги
TAG_NAME_LENGTH = 200
TAG_SLUG_LENGTH = 200

# Рецепты
RECIPE_NAME_LENGTH = 200

COOKING_TIME_MIN_VALUE = 1
COOKING_TIME_MAX_VALUE = 32000


# RecipeIngredient
AMOUNT_MIN_VALUE = 1
AMOUNT_MAХ_VALUE = 32000

"""
Константы для моделей users
"""
FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150
USERNAME_MAX_LENGTH = 150
PASSWORD_MAX_LENGTH = 150
