# Generated by Django 4.2.4 on 2023-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsum',
            options={'ordering': ['ingredient'], 'verbose_name': 'Ингредиент в рецептах с количеством'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Рецепт'},
        ),
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='unique_favorite_model',
        ),
        migrations.RemoveConstraint(
            model_name='ingredientsum',
            name='unique_amountingredient_model',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=200, verbose_name='Единицы измерения ингредиента'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, verbose_name='HEX-код тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='Слаг тега'),
        ),
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='ingredientsum',
            constraint=models.UniqueConstraint(fields=('ingredient', 'amount'), name='unique_amountingredient'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'color', 'slug'), name='unique_name_color_slug'),
        ),
    ]
