# Generated by Django 4.2.7 on 2023-12-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient_fields',
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag_fields',
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredient_fields', violation_error_message={'name, measurement_unit': 'Поля не уникальны'}),
        ),
    ]
